const router = require('express').Router();
const { verifyToken } = require('../utils/verifyToken');
const { create, update, delete_document, getList, get_category } = require("../Controllers/document_controller");
const { uploadMulti } = require("../utils/file");
router.get('/list/:id', verifyToken, getList);
// router.get('/list/:id',getListByID);
router.post('/create', verifyToken, uploadMulti, create);
router.put('/update', verifyToken, uploadMulti, update);
router.delete('/delete/:id', delete_document);
router.get('/list-cate', get_category);
module.exports = router;